version: '3.7'
services:
  mysqldb-user-service:
    restart: always
    image: 'mariadb:10.7.8'
    container_name: mysqldb-user-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service
